# Generated by Django 2.1.7 on 2019-04-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='miniondata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SwapTotal', models.DecimalField(decimal_places=2, max_digits=19)),
                ('SwapFree', models.DecimalField(decimal_places=2, max_digits=19)),
                ('MemFree', models.DecimalField(decimal_places=2, max_digits=19)),
                ('MemTotal', models.DecimalField(decimal_places=2, max_digits=19)),
                ('grading_size', models.DecimalField(decimal_places=2, max_digits=19)),
                ('boot_size', models.DecimalField(decimal_places=2, max_digits=19)),
                ('home_szie', models.DecimalField(decimal_places=2, max_digits=19)),
                ('swaptmp_szie', models.DecimalField(decimal_places=2, max_digits=19)),
                ('gen_available', models.DecimalField(decimal_places=2, max_digits=19)),
                ('boot_available', models.DecimalField(decimal_places=2, max_digits=19)),
                ('home_available', models.DecimalField(decimal_places=2, max_digits=19)),
                ('swaptmp_available', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cpulod15_min', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cpulod5_min', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cpulod1_min', models.DecimalField(decimal_places=2, max_digits=19)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='systemmsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osfinger', models.CharField(max_length=30)),
                ('osarch', models.CharField(max_length=30)),
                ('kernelrelease', models.CharField(max_length=30)),
                ('cpu_model', models.CharField(max_length=40)),
                ('num_cpus', models.CharField(max_length=30)),
                ('mac_interfaces', models.CharField(max_length=30)),
                ('hostname', models.CharField(max_length=30)),
                ('masterip', models.CharField(max_length=30)),
                ('nameid', models.CharField(max_length=30)),
            ],
        ),
    ]
