# Generated by Django 2.1.7 on 2019-03-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sysmsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biosversion', models.CharField(max_length=30)),
                ('kernelrelease', models.CharField(max_length=30)),
                ('os', models.CharField(max_length=30)),
                ('cpu_model', models.CharField(max_length=30)),
                ('host', models.CharField(max_length=30)),
                ('ip_interfaces', models.CharField(max_length=30)),
            ],
        ),
    ]
