# Generated by Django 2.1.7 on 2019-03-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
